### ISSUE TITLE
Mask doesn't match DTI when using the testdata provided

### ISSUE THREAD

**Issue by cowry09** [maswendt/AIDAmri#4]
![image](https://user-images.githubusercontent.com/50677308/99919745-487db000-2ced-11eb-933f-d0823a0d3cd9.png)
I was at the reconstruction step for fiber tractography using the automatically generated mask. I saw the mask for DTI data was off.
It seems this issue has to do with the "np.flip" steps in the T2w and DTI preprocessing.
[testDataSmoothMicoBetMask_scaled.nii.gz](https://github.com/maswendt/AIDAmri/files/5580576/testDataSmoothMicoBetMask_scaled.nii.gz)
[testData_mcf.nii.gz.src.gz](https://github.com/maswendt/AIDAmri/files/5580577/testData_mcf.nii.gz.src.gz)

**Comment by maswendt** [comment]
That's correct, the current mask generated by T2w or DTI preprocessing needs to be flipped e.g. for DSIStudio (to make it more complicated this is because the DSIStudio calculates everything based on the original Bruker2NII file - the file which is not brain extracted, motion-corrected, .., and flipped). But be aware that the mask then will not fit to the originally processed *MicoBet.nii.gz file. We will flip the mask to make it more convenient to use in v1.1. A workaround in v1.0 would be to use the mask function in DSIStudio (which is a simple threshold mask but works quite well).
